# Generated by Django 4.2.1 on 2024-04-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecut',
            name='out_img',
            field=models.ImageField(blank=True, upload_to='out_imgs'),
        ),
    ]
