# Generated by Django 4.2.1 on 2024-04-03 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('main', '0003_alter_imagecut_out_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecut',
            name='session',
            field=models.ForeignKey(blank=True, default=123, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
            preserve_default=False,
        ),
    ]
