# Generated by Django 4.2.1 on 2024-04-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_imagecut_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecut',
            name='session',
        ),
    ]
